# Generated by Django 4.2.5 on 2023-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entertainment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('groceries', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subscriptions', models.DecimalField(decimal_places=2, max_digits=8)),
                ('emis', models.DecimalField(decimal_places=2, max_digits=8)),
                ('other', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12)),
                ('stocks', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assets', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('principle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tenure', models.IntegerField()),
                ('emi', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
