# Generated by Django 4.2.5 on 2023-09-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_expenses_emis_alter_expenses_entertainment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investments',
            name='savings',
        ),
    ]
