# Generated by Django 4.2.5 on 2023-09-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_investments_savings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='other',
            new_name='something',
        ),
    ]
