# Generated by Django 4.2.5 on 2023-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_expenses_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
