# Generated by Django 4.2.5 on 2023-09-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_investment_month_investment_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='end',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='principle',
        ),
    ]
