# Generated by Django 4.2.5 on 2023-09-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_expense_shoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
