# Generated by Django 4.2.5 on 2023-10-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_expense_fuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='month',
            new_name='yyyymm',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='year',
        ),
    ]
