# Generated by Django 4.2.5 on 2023-10-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_month_investment_yyyymm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='entertainment',
        ),
    ]
