# Generated by Django 4.2.5 on 2023-10-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_month_expense_yyyymm_remove_expense_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='msg',
            field=models.CharField(default='0', max_length=40),
            preserve_default=False,
        ),
    ]
